name: Generate Podcast Feeds
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Verify feed.py is present
        run: ls -la $GITHUB_WORKSPACE
      
      - name: Check current directory
        run: pwd
      - name: List files to verify feed.py
        run: ls -la
      
      - name: Run Feed Generator
        run: python $GITHUB_WORKSPACE/feed.py
      - name: Push Repo Changes (if any)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Modified Feed"
          git push

            
